# Define the I/O pahts. Supports relative paths
dataset_path: 'data/cleaned/pubs_with_domain.csv'
dataset_path_sample_gold_standard: 'data/cleaned/sampled_pubs_for_gold_standard.csv'
output_filename: 'data/output/author_relations.csv'

# If True, use the dataset "data/cleaned/sampled_pubs_for_gold_standard.csv" over the full dataset
use_sample_for_gold_standard: false

# Which subset of the dataset to use. Possible values: "biomedical_recent" or empty for all.
domain:

# Chunk number. 
# If empty, take a random sample.
# If number the nth chunk of nrows will be taken.
# First index is 0
chunk:

# Number of rows to read from the dataset. 
# If empty, take the full dataset
# If use_sample_for_gold_standard == true, sampling will be skipped 
nrows:

# Choose rank after which we cut of contributors.
# 1 means we only keep the first, 2 the first two etc.
min_rank_contrib:
